// lib/services/english_phrase_service.dart
import 'dart:math';

import 'package:ongi/src/core/constants/emotion_category.dart';
import 'package:ongi/src/features/home/services/phrase_service.dart';

class EnglishPhraseService implements PhraseService {
  final Random _random = Random();

  static const Map<EmotionCategory, List<String>> _phrases = {
    EmotionCategory.general: [
      "You've worked so hard today.",
      "You're doing great.",
      "Take a moment to breathe and look up at the sky.",
      "Don't forget the small joys around you.",
      "You are special just by being you.",
      "It's okay to put down your worries for a while.",
      "Warm your heart with a cup of hot tea.",
      "I hope today is the kindest day for you.",
      "Start by believing in yourself.",
      "You are much stronger than you think.",
      "It's okay, not everything has to be perfect.",
      "You are safe in this moment.",
      "Your smile brightens the world.",
      "Praise yourself even for small successes.",
      "I'm cheering for you as you grow a little each day.",
      "All your efforts today have meaning.",
      "Sometimes, it's okay to do nothing at all.",
      "I pray for your heart to find peace.",
      "May all the good energy in the world flow to you.",
      "You were born to be loved.",
      "Don't worry, everything will be alright.",
      "May your day be filled with only good things.",
      "Your potential is limitless.",
      "You can shine in any situation.",
      "Nurture the small spark in your heart into hope.",
      "You are a precious being, perfect as you are.",
      "The emotions you're feeling now are all natural.",
      "Go slowly, at your own pace.",
      "Sometimes, resting is the way to go further.",
      "I will always support your dreams.",
      "You deserve to have a wonderful day today.",
      "If you had a tough time, only good things will happen from now on.",
      "Your life will be filled with beautiful stories.",
      "It's okay to be a little more lenient with yourself.",
      "You have the power within you to change the world.",
      "May you be the happiest person today.",
      "Every moment will teach you something.",
      "It's okay to get lost sometimes; you can find a new path.",
      "Your warm heart makes the world more beautiful.",
      "I admire you for moving forward step by step.",
      "You are much more lovable than you think.",
      "Prepare a small gift for yourself today.",
      "Listen to your heart; the answer might be there.",
      "You are not alone; there are always people who support you.",
      "May all the beautiful things in the world be with you.",
      "Today's difficulties will make you grow stronger.",
      "You are worthy of love.",
      "May the comfort you need most be delivered to you today.",
      "It's okay to fall; you have the strength to get up again.",
      "Your life is a work of art you create.",
      "May this moment of peace be with you.",
      "May all your days be peaceful.",
      "Small changes can bring great happiness.",
      "Open the window of your heart and breathe in fresh air.",
      "You deserve to rest enough.",
      "Trust your choices today.",
      "Try to have a grateful heart for your life.",
      "Everything will find its place.",
      "You are already shining brightly enough.",
      "Embrace your heart warmly today.",
      "The most important thing is you.",
      "You are beautiful just as you are.",
      "Love yourself today.",
      "Every morning is a new opportunity.",
      "Plant beautiful flowers in the garden of your heart.",
      "No difficulty can stop you.",
      "You are the protagonist of your life.",
      "Positive thoughts bring positive results.",
      "Your future is shining brightly.",
      "You did your best today too.",
      "Quietly close your eyes and listen to your inner voice.",
      "You are a unique and precious being in this world.",
      "The path you are walking now is the right one.",
      "Your efforts will surely bear fruit someday.",
      "Good times always follow hard times.",
      "You fully deserve love and happiness.",
      "Tell yourself 'thank you' today.",
      "Your life is full of miracles.",
      "Put your worries aside for a moment and enjoy the present.",
      "You are growing into a better person every day.",
      "Go where your heart leads you.",
      "The world is on your side.",
      "You can achieve anything you want.",
      "Everything you experienced today is a valuable asset.",
      "Your life is like a beautiful song.",
      "Let go of your burdens and move forward lightly.",
      "You are strong and brave enough.",
      "May a small joy find you today.",
      "Keep moving towards your dreams.",
      "Everything is prepared for you.",
      "You can always make the right choice.",
      "Breathe positive energy into your life.",
      "You sparkled brightly today too.",
      "May peace dwell in your heart.",
      "You are an artist who can make your life beautiful.",
      "Today, your best friend is yourself.",
      "You are the light and salt of this world.",
      "Live cherishing every moment.",
      "You are wonderful enough just as you are.",
      "May your day be filled with love and laughter.",
    ],
    EmotionCategory.anger: [
      "It's perfectly normal to be angry right now. It's not your fault.",
      "Stop everything for a moment and take a deep breath.",
      "This anger will eventually pass.",
      "You have the strength to manage your emotions.",
      "I understand your angry heart. Take a break.",
      "The situation made you feel this way, but you're still a good person.",
      "This emotion doesn't define all of you.",
      "It's okay. I'll wait until your anger subsides.",
      "You don't have to suppress it, but let's find a healthy way to express it.",
      "It's better not to make any decisions right now.",
      "A warm glass of water might help.",
      "Once this wave of intense emotion passes, calmness will come.",
      "You are much bigger than this emotion.",
      "Getting angry doesn't mean you're weak. It means you've been through a lot.",
      "Vent your feelings in a safe place.",
      "After this moment passes, you'll be able to smile again.",
      "Stay away from what hurt your heart for a while.",
      "It's okay, you can get through this situation.",
      "Behind anger, there might be a wounded heart. Take care of that heart.",
      "Even if the world seems to be testing you, you can overcome it.",
      "This feeling is temporary, so don't get too lost in it.",
      "You are precious. No emotion can diminish your value.",
      "It's okay to stay here until your anger cools down.",
      "It's not your fault. The external situation was just difficult.",
      "For now, just focus on calming your mind.",
      "This too shall pass. A clear sky awaits after the storm.",
      "You are a strong person. You can handle this emotion well.",
      "Don't judge anything right now, just let yourself feel.",
      "When you're angry, try pausing and counting to ten.",
      "I'll help you find your peace again.",
      "Feeling such emotions is perfectly human.",
      "You're angry because you were hurt. Comfort your heart first.",
      "You can be the master of this emotion.",
      "Anger can sometimes be a signal telling us something.",
      "This discomfort can make you grow.",
      "You are not alone. There are people who understand this feeling.",
      "A day might come when you look back at this moment and smile.",
      "Protecting your heart is the most important thing right now.",
      "Step back from this emotion and observe it.",
      "You have the wisdom to solve this situation.",
      "When the anger subsides, everything will look different.",
      "You are fully deserving of love, regardless of this feeling.",
      "There's a peaceful space within you. Try to find it.",
      "This emotion cannot take away your strength.",
      "It's okay, every emotion has its reason for being.",
      "For now, just accept your emotions as they are.",
      "Remember that this moment is not your entirety.",
      "You have the courage to overcome this emotion.",
      "Don't blame yourself too much for being angry.",
      "You are still valuable and a wonderful person.",
      "This storm of emotion will pass, revealing a calm sea.",
      "None of this started because of your fault.",
      "Close your eyes for a moment and imagine a peaceful place.",
      "Anger is just a temporary guest. It will leave soon.",
      "You are wise enough to manage this emotion.",
      "Right now, it's better to calm your mind quietly than to say anything.",
      "You can transform the fire in your heart into healthy energy.",
      "This too shall pass. You will be okay.",
      "Even your angry self is a part of you. Embrace that too.",
      "This emotion might be a signal for you. See what you need.",
      "Pause for a moment and listen to what your body and mind want.",
      "It's okay, this emotion won't hurt you.",
      "You have the inner strength to overcome this situation.",
      "The angrier you get, be kinder to yourself.",
      "This emotion is not meant to drain your energy.",
      "You are stronger than this emotion. Believe it.",
      "When the anger clears, you'll see a new perspective.",
      "Your peace of mind is most important.",
      "Find a healthy way to release this emotion. A walk is good.",
      "It's okay. Everything will return to its place.",
      "You are not alone. People who understand this emotion are by your side.",
      "Remember that this emotion is not your fault.",
      "Take a break and listen to your favorite music.",
      "Anger is a natural emotion. Don't feel too guilty.",
      "This emotion might be a signal to protect yourself.",
      "You are strong enough to overcome this emotion.",
      "When the anger subsides, you'll be able to see the situation more clearly.",
      "Find an activity that can calm your mind.",
      "This emotion is not permanent. It will pass soon.",
      "You are still loved and a valuable being.",
      "For now, just take a breath and focus on calming your mind.",
      "It's not your fault. You did your best.",
      "Wait until this wave of emotion becomes calm.",
      "When you're angry, think of people who support you.",
      "You can grow stronger through this emotion.",
      "It's okay. Respect all the emotions you're feeling right now.",
      "This emotion is just a part of you, not your whole self.",
      "You can find peace. Slowly, one step at a time.",
      "Anger can sometimes be a powerful motivator for change.",
      "Embrace your heart warmly. Because you are precious.",
      "This emotion will make you stronger.",
      "Don't force anything right now. Let it flow naturally.",
      "You have the wisdom and courage to get through this.",
      "What you need when you're angry isn't blame, but understanding and comfort.",
      "When this emotion passes, you will be even stronger.",
      "You are by no means weak. The emotion you're feeling is natural.",
      "It's okay, calmness will be waiting at the end of this emotion.",
      "My heart will always be with you until your mind finds peace again.",
      "This emotion is not your fault, so don't blame yourself.",
    ],
    EmotionCategory.sad: [
      "It's okay to be sad right now. You can grieve as much as you want.",
      "You are not alone. I am, we are here for you.",
      "This sadness will also pass. Just hang in there a little longer.",
      "If tears come, don't hold them back. Let them flow. It might lighten your heart.",
      "I can't fully understand your pain, but I offer my sincerest condolences.",
      "Like the saying 'time heals all wounds,' this sadness will gradually fade.",
      "You are a precious person worthy of enough love.",
      "I hope you don't stay in sadness for too long. You have the right to be happy.",
      "I want to wrap your heart like a warm blanket.",
      "It's okay if not everything gets better at once.",
      "If you don't want to do anything, that's okay. You can rest now.",
      "After this darkness passes, a bright morning will surely come.",
      "It's not your fault. Sadness can come to anyone.",
      "May a little comfort be a great strength to your heart.",
      "You are strong enough to overcome this sadness.",
      "Sadness will make you a deeper person.",
      "For now, don't think about anything and just focus on taking care of your heart.",
      "I want to lighten the weight of this sadness, even if just a little.",
      "I'll be with you until the day you can smile again.",
      "Remember, you are still beautiful and valuable.",
      "When sadness washes over you, think of the people who love you.",
      "This sadness is not all of you. You have more shining parts within you.",
      "Warm sunlight will eventually shine on your heart too.",
      "It's tough now, but it will definitely get better. I promise.",
      "I don't judge you for feeling sad. I just want to hug you.",
      "This painful time will eventually become a foundation for your growth.",
      "You are not alone. Somewhere in this world, there's a heart that understands you.",
      "Light is surely waiting at the end of the tunnel of sadness.",
      "For now, just accept your sadness as it is.",
      "I'll quietly stay by your side until your tears dry.",
      "I hope you can find small joys even in sadness.",
      "You are precious. Your value doesn't change because of this sadness.",
      "When this sadness passes, you will be more mature.",
      "I pray for your heart to find peace again.",
      "For now, pause and fully feel your emotions.",
      "It's okay. Sadness can be a part of the healing process.",
      "You can stand up again. Slowly, at your own pace.",
      "This sadness will make you stronger. Believe it.",
      "Find something that can comfort your heart. Music, movies, or a talk with a friend.",
      "Sadness is a natural emotion. Don't push yourself too hard.",
      "You have the strength to endure this sadness. Believe in your inner strength.",
      "It may seem dark now, but the sun will surely rise again.",
      "I don't take your sadness lightly. I respect its depth.",
      "May this time of sadness be a time of rest and recovery for you.",
      "It's okay to cry enough. Tears are not a sign of weakness.",
      "Don't let sadness consume you. You are stronger than that.",
      "You are loved. Even in this moment.",
      "When this sadness passes, a new chapter will unfold in your life.",
      "Wait patiently until your heart recovers.",
      "You can overcome this sadness and move towards a brighter future.",
      "Sadness doesn't define you. You are more than that.",
      "It's okay, this sadness will be an opportunity to understand yourself more deeply.",
      "Just as your tears become stars brightening the night sky, sadness too will have meaning.",
      "For now, just listen to your heart. What does it want?",
      "This sadness will make you a warmer person.",
      "You are not alone. There are people who will share this sadness with you.",
      "Time will heal all wounds. Just endure a little longer.",
      "May the sadness in your heart melt away like snow.",
      "Even if it's hard now, a day to smile again will surely come.",
      "You will become stronger through this sadness.",
      "Sadness sometimes teaches us precious things.",
      "Take some quiet time for your heart to rest.",
      "This sadness is not your fault. It can happen to anyone.",
      "You are worthy of enough love. Unchanged even in sadness.",
      "When you pass through this dark tunnel, you will meet a brighter light.",
      "I will try to understand your sadness. Tell me anytime.",
      "For now, just feel your emotions as they are. It's okay.",
      "This sadness can temporarily stop your life, but it can't end it.",
      "You can be happy again. Don't lose that belief.",
      "Sadness is like a passing cloud. A clear sky will soon be visible.",
      "I send warm comfort so your heart can heal.",
      "This sadness will make you grow into a deeper and wider person.",
      "You are not alone. Even in unseen places, people are cheering for you.",
      "It's hard now, but this too shall pass. Cheer up.",
      "I respect your sadness. And I'll cheer for you to stand up again.",
      "This sadness can be an opportunity for your growth.",
      "You are strong enough to handle this sadness.",
      "For now, just pat your heart. Tell it 'good job'.",
      "Sadness is not eternal. Don't lose hope.",
      "You are still shining. Even behind the shadow of sadness.",
      "You will become more mature through this sadness.",
      "I earnestly hope your heart will be filled with joy again.",
      "Sadness sometimes leads us to deeper places. You can discover a new you there.",
      "For now, just rest. Your heart needs time to recover.",
      "You were born to be loved. This sadness cannot change that fact.",
      "May greater happiness bloom where this sadness has passed.",
      "You are a precious being. No sadness can diminish your value.",
      "It's okay to shed tears now. Those tears will cleanse your heart.",
      "This sadness will not break you. You will rise again.",
      "I will always be by your side until your heart finds peace.",
      "Sadness is not your fault. It's just proof that you have such a pure and tender heart.",
      "This experience of sadness will make you a more empathetic person.",
      "You are not alone. There are people who understand and support your sadness.",
      "It's hard now, but growth will surely await at the end of this sadness.",
      "You will overcome this sadness and become an even more radiant person.",
      "Sadness sometimes makes us realize the value of true happiness.",
      "May your heart become bright and sunny again like a warm spring day.",
      "This sadness is just a fleeting shadow in your life. It will soon lift.",
      "You are still strong and beautiful. Your light doesn't go out even in sadness.",
    ],
    EmotionCategory.afraid: [
      "The fear you're feeling now is natural. It's not your fault.",
      "You are not alone. I will stay by your side.",
      "This fear will also pass. You are safe.",
      "Try taking deep breaths. Breathing out slowly will help calm your mind.",
      "You are much stronger and braver than you think.",
      "Instead of fighting fear, just be with it. It will soon diminish.",
      "In this moment, you are in a safe place.",
      "Just as a small light can illuminate deep darkness, small courage can overcome great fear.",
      "It's okay. It's normal for everything to feel uncertain sometimes.",
      "Don't let this anxiety dominate all of you.",
      "You already have the strength within you to overcome this fear.",
      "One step at a time, even a very small step is fine. What's important is that you're moving forward.",
      "Fear can be a sign that an opportunity for growth has come.",
      "I'll help your heart find peace.",
      "Don't worry. Everything will eventually work out fine.",
      "You are protected. Nothing can harm you carelessly.",
      "Don't let this fear block your potential.",
      "Try holding something warm or listening to comforting music.",
      "It's okay, fear is like a shadow without substance.",
      "You are precious. This fear doesn't diminish your value.",
      "Try talking honestly about your feelings to someone.",
      "This too shall pass. The anxiety you feel now is not forever.",
      "You've overcome many difficulties before. You can do it this time too.",
      "Fear is just a natural reaction to the unknown.",
      "Think of the people who support and love you.",
      "When this fear subsides, the world will look bright again.",
      "It's okay not to decide anything right now. Wait until your mind calms down.",
      "You are safe, loved, and supported.",
      "This fear might not be to stop you, but to make you look back for a moment.",
      "You are brave. You, who try to move forward even while feeling fear, are truly brave.",
      "Believe that everything will be okay. That belief will be your strength.",
      "You have the ability to control this situation.",
      "Fear often feels exaggerated, bigger than it really is.",
      "Find a peaceful place in your mind and stay there for a while.",
      "This fear will make you stronger and wiser.",
      "It's okay. Respect all the emotions you're feeling right now.",
      "Remember that you are not alone. There's always someone on your side.",
      "When this wave of fear passes, you will see a calm sea.",
      "Listen to your inner voice. The answer might be there.",
      "Fear can be a stepping stone for your growth.",
      "For now, just focus on feeling safe.",
      "You have enough potential to overcome this fear.",
      "The world can feel scary at times, but there's always hope by your side.",
      "Fear can sometimes be a signal announcing the beginning of change.",
      "You are fully deserving of love. Fear cannot hide that fact.",
      "When this moment passes, you will be even more courageous.",
      "You are by no means weak. Feeling fear is human.",
      "It's okay. A new beginning might be waiting at the end of this fear.",
      "This space will protect you so your heart can find peace again.",
      "Fear is not your fault. Sometimes the world changes too fast.",
      "This fear is not a wall to stop you, but a hurdle to jump over.",
      "You are safe. For this moment, it's okay to let go of all worries.",
      "Fear is just your shadow, not you yourself.",
      "It's okay, this anxiety will soon pass. You can find peace again.",
      "There's a seed of courage within you. Water it and give it sunshine.",
      "Don't let this fear hide your light. You can still shine brightly.",
      "One step at a time, go slowly. There's no need to rush.",
      "You have both the wisdom and strength to handle this fear.",
      "Fear often seems to test how brave we can be.",
      "For now, just catch your breath and feel the ground firm beneath your feet.",
      "You are not alone. There's someone you can share this fear with.",
      "Remember that this fear is not your fault. This isn't on you.",
      "Close your eyes for a moment and recall the most comfortable moment you've had.",
      "Fear is a natural emotion. Feeling it doesn't mean you're weak.",
      "This fear might be a signal to protect you. See what you need.",
      "You are strong enough to overcome this fear. Believe in yourself.",
      "When the fear subsides, you'll be able to see the situation more clearly.",
      "Find a safe activity that can calm your mind.",
      "This fear is not permanent. It will disappear someday.",
      "You are still loved and a valuable being, even in fear.",
      "For now, just acknowledge your emotion and watch it pass.",
      "It's not your fault. You are already doing your best.",
      "It's okay to stay here until this wave of fear calms down.",
      "When you're scared, think of the faces of those who support and love you.",
      "You can grow and become stronger through this fear.",
      "It's okay. Every emotion you feel now is a part of you. Treat it preciously.",
      "This fear doesn't define you. You are much greater than that.",
      "You can find peace. Very slowly, at your own pace.",
      "Fear sometimes signals us to explore new paths.",
      "Embrace your heart warmly. You deserve it.",
      "This fear will make you tougher. You can overcome it.",
      "Don't force anything right now. Let your mind flow naturally.",
      "You already have everything you need to get through this. Within you.",
      "What you need when you're scared isn't blame, but warm encouragement and support.",
      "When this fear passes, you will have grown a bit taller.",
      "You are by no means weak. Fear is just a prelude to courage.",
      "It's okay, peace and stability will surely be waiting at the end of this fear.",
      "This space will always be with you so your heart can feel safe again.",
      "This fear is not your fault, so please don't blame yourself. You are precious.",
    ],
  };

  @override
  List<String> getPhrasesForCategory(EmotionCategory category) {
    return _phrases[category] ??
        _phrases[EmotionCategory.general] ??
        ["Don't worry, everything will be alright."];
  }

  @override
  String getRandomPhraseForCategory(EmotionCategory category) {
    final List<String> categoryPhrases = getPhrasesForCategory(category);
    if (categoryPhrases.isEmpty) {
      final List<String> generalPhrases = getPhrasesForCategory(
        EmotionCategory.general,
      );
      if (generalPhrases.isEmpty) {
        return "Don't worry, everything will be alright.";
      }
      return generalPhrases[_random.nextInt(generalPhrases.length)];
    }
    return categoryPhrases[_random.nextInt(categoryPhrases.length)];
  }
}
