// lib/services/korean_phrase_service.dart
import 'dart:math';

import 'package:ongi_app/src/core/constants/emotion_category.dart';
import 'package:ongi_app/src/features/home/services/phrase_service.dart';

class SpanishPhraseService implements PhraseService {
  final Random _random = Random();

  static const Map<EmotionCategory, List<String>> _phrases = {
    EmotionCategory.general: [
      "Has trabajado muy duro hoy.",
      "Lo estás haciendo genial.",
      "Tómate un momento para respirar y mirar al cielo.",
      "No olvides las pequeñas alegrías que te rodean.",
      "Eres especial solo por ser tú.",
      "Está bien dejar de lado tus preocupaciones por un rato.",
      "Calienta tu corazón con una taza de té caliente.",
      "Espero que hoy sea el día más amable para ti.",
      "Empieza por creer en ti mismo/a.",
      "Eres mucho más fuerte de lo que piensas.",
      "Está bien, no todo tiene que ser perfecto.",
      "Estás a salvo en este momento.",
      "Tu sonrisa ilumina el mundo.",
      "Felicítate incluso por los pequeños éxitos.",
      "Te animo mientras creces un poco cada día.",
      "Todos tus esfuerzos de hoy tienen significado.",
      "A veces, está bien no hacer nada en absoluto.",
      "Rezo para que tu corazón encuentre la paz.",
      "Que toda la buena energía del mundo fluya hacia ti.",
      "Naciste para ser amado/a.",
      "No te preocupes, todo saldrá bien.",
      "Que tu día esté lleno solo de cosas buenas.",
      "Tu potencial es ilimitado.",
      "Puedes brillar en cualquier situación.",
      "Cultiva la pequeña chispa en tu corazón hasta convertirla en esperanza.",
      "Eres un ser precioso, perfecto/a tal como eres.",
      "Las emociones que sientes ahora son todas naturales.",
      "Ve despacio, a tu propio ritmo.",
      "A veces, descansar es la forma de llegar más lejos.",
      "Siempre apoyaré tus sueños.",
      "Mereces tener un día maravilloso hoy.",
      "Si tuviste un momento difícil, a partir de ahora solo pasarán cosas buenas.",
      "Tu vida se llenará de hermosas historias.",
      "Está bien ser un poco más indulgente contigo mismo/a.",
      "Tienes el poder dentro de ti para cambiar el mundo.",
      "Que hoy seas la persona más feliz.",
      "Cada momento te enseñará algo.",
      "Está bien perderse a veces; puedes encontrar un nuevo camino.",
      "Tu cálido corazón hace el mundo más bello.",
      "Te admiro por avanzar paso a paso.",
      "Eres mucho más adorable de lo que piensas.",
      "Prepárate un pequeño regalo hoy.",
      "Escucha a tu corazón; la respuesta podría estar allí.",
      "No estás solo/a; siempre hay personas que te apoyan.",
      "Que todas las cosas bellas del mundo estén contigo.",
      "Las dificultades de hoy te harán más fuerte.",
      "Eres digno/a de amor.",
      "Que el consuelo que más necesitas te llegue hoy.",
      "Está bien caer; tienes la fuerza para levantarte de nuevo.",
      "Tu vida es una obra de arte que tú creas.",
      "Que este momento de paz esté contigo.",
      "Que todos tus días sean pacíficos.",
      "Pequeños cambios pueden traer gran felicidad.",
      "Abre la ventana de tu corazón y respira aire fresco.",
      "Mereces descansar lo suficiente.",
      "Confía en tus elecciones de hoy.",
      "Intenta tener un corazón agradecido por tu vida.",
      "Todo encontrará su lugar.",
      "Ya estás brillando lo suficientemente fuerte.",
      "Abraza tu corazón cálidamente hoy.",
      "Lo más importante eres tú.",
      "Eres hermoso/a tal como eres.",
      "Ámate a ti mismo/a hoy.",
      "Cada mañana es una nueva oportunidad.",
      "Planta hermosas flores en el jardín de tu corazón.",
      "Ninguna dificultad puede detenerte.",
      "Eres el/la protagonista de tu vida.",
      "Los pensamientos positivos traen resultados positivos.",
      "Tu futuro brilla intensamente.",
      "Hoy también diste lo mejor de ti.",
      "Cierra los ojos en silencio y escucha tu voz interior.",
      "Eres un ser único y precioso en este mundo.",
      "El camino que estás recorriendo ahora es el correcto.",
      "Tus esfuerzos seguramente darán fruto algún día.",
      "Los buenos tiempos siempre siguen a los tiempos difíciles.",
      "Mereces plenamente el amor y la felicidad.",
      "Dite 'gracias' a ti mismo/a hoy.",
      "Tu vida está llena de milagros.",
      "Deja tus preocupaciones a un lado por un momento y disfruta el presente.",
      "Estás creciendo como una mejor persona cada día.",
      "Ve a donde te lleve tu corazón.",
      "El mundo está de tu lado.",
      "Puedes lograr cualquier cosa que desees.",
      "Todo lo que experimentaste hoy es un activo valioso.",
      "Tu vida es como una hermosa canción.",
      "Suelta tus cargas y avanza ligermente.",
      "Eres lo suficientemente fuerte y valiente.",
      "Que una pequeña alegría te encuentre hoy.",
      "Sigue avanzando hacia tus sueños.",
      "Todo está preparado para ti.",
      "Siempre puedes tomar la decisión correcta.",
      "Insufla energía positiva en tu vida.",
      "Hoy también brillaste intensamente.",
      "Que la paz habite en tu corazón.",
      "Eres un/a artista que puede embellecer tu vida.",
      "Hoy, tu mejor amigo/a eres tú mismo/a.",
      "Eres la luz y la sal de este mundo.",
      "Vive apreciando cada momento.",
      "Eres maravilloso/a tal como eres.",
      "Que tu día esté lleno de amor y risas.",
    ],
    EmotionCategory.anger: [
      "Es perfectamente normal estar enfadado/a ahora. No es tu culpa.",
      "Detén todo por un momento y respira profundamente.",
      "Este enfado también pasará.",
      "Tienes la fuerza para manejar tus emociones.",
      "Entiendo tu corazón enfadado. Tómate un descanso.",
      "La situación te hizo sentir así, pero sigues siendo una buena persona.",
      "Esta emoción no te define por completo.",
      "Está bien. Esperaré hasta que tu enfado disminuya.",
      "No tienes que reprimirlo, pero busquemos una forma saludable de expresarlo.",
      "Es mejor no tomar ninguna decisión ahora mismo.",
      "Un vaso de agua tibia podría ayudar.",
      "Una vez que pase esta ola de emoción intensa, vendrá la calma.",
      "Eres mucho más grande que esta emoción.",
      "Enfadarse no significa que seas débil. Significa que has pasado por mucho.",
      "Desahoga tus sentimientos en un lugar seguro.",
      "Después de que pase este momento, podrás sonreír de nuevo.",
      "Aléjate por un tiempo de lo que hirió tu corazón.",
      "Está bien, puedes superar esta situación.",
      "Detrás del enfado, podría haber un corazón herido. Cuida ese corazón.",
      "Incluso si el mundo parece estar poniéndote a prueba, puedes superarlo.",
      "Este sentimiento es temporal, así que no te pierdas demasiado en él.",
      "Eres precioso/a. Ninguna emoción puede disminuir tu valor.",
      "Está bien quedarte aquí hasta que tu enfado se calme.",
      "No es tu culpa. La situación externa simplemente fue difícil.",
      "Por ahora, solo concéntrate en calmar tu mente.",
      "Esto también pasará. Un cielo despejado espera después de la tormenta.",
      "Eres una persona fuerte. Puedes manejar bien esta emoción.",
      "No juzgues nada ahora mismo, solo permítete sentir.",
      "Cuando estés enfadado/a, intenta detenerte y contar hasta diez.",
      "Te ayudaré a encontrar tu paz de nuevo.",
      "Sentir tales emociones es perfectamente humano.",
      "Estás enfadado/a porque te hirieron. Consuela primero tu corazón.",
      "Puedes ser el/la dueño/a de esta emoción.",
      "El enfado a veces puede ser una señal que nos dice algo.",
      "Esta incomodidad puede hacerte crecer.",
      "No estás solo/a. Hay personas que entienden este sentimiento.",
      "Podría llegar un día en que mires atrás a este momento y sonrías.",
      "Proteger tu corazón es lo más importante ahora mismo.",
      "Aléjate de esta emoción y obsérvala.",
      "Tienes la sabiduría para resolver esta situación.",
      "Cuando el enfado disminuya, todo se verá diferente.",
      "Mereces plenamente el amor, independientemente de este sentimiento.",
      "Hay un espacio pacífico dentro de ti. Intenta encontrarlo.",
      "Esta emoción no puede quitarte tu fuerza.",
      "Está bien, cada emoción tiene su razón de ser.",
      "Por ahora, solo acepta tus emociones tal como son.",
      "Recuerda que este momento no es tu totalidad.",
      "Tienes el coraje para superar esta emoción.",
      "No te culpes demasiado por estar enfadado/a.",
      "Sigues siendo valioso/a y una persona maravillosa.",
      "Esta tormenta de emoción pasará, revelando un mar en calma.",
      "Nada de esto comenzó por tu culpa.",
      "Cierra los ojos por un momento e imagina un lugar pacífico.",
      "El enfado es solo un invitado temporal. Pronto se irá.",
      "Eres lo suficientemente sabio/a para manejar esta emoción.",
      "Ahora mismo, es mejor calmar tu mente en silencio que decir cualquier cosa.",
      "Puedes transformar el fuego en tu corazón en energía saludable.",
      "Esto también pasará. Estarás bien.",
      "Incluso tu yo enfadado/a es parte de ti. Acéptalo también.",
      "Esta emoción podría ser una señal para ti. Observa lo que necesitas.",
      "Detente un momento y escucha lo que tu cuerpo y mente quieren.",
      "Está bien, esta emoción no te hará daño.",
      "Tienes la fuerza interior para superar esta situación.",
      "Cuanto más te enfades, sé más amable contigo mismo/a.",
      "Esta emoción no está destinada a agotar tu energía.",
      "Eres más fuerte que esta emoción. Créelo.",
      "Cuando el enfado se disipe, verás una nueva perspectiva.",
      "Tu paz mental es lo más importante.",
      "Encuentra una forma saludable de liberar esta emoción. Un paseo es bueno.",
      "Está bien. Todo volverá a su lugar.",
      "No estás solo/a. Personas que entienden esta emoción están a tu lado.",
      "Recuerda que esta emoción no es tu culpa.",
      "Tómate un descanso y escucha tu música favorita.",
      "El enfado es una emoción natural. No te sientas demasiado culpable.",
      "Esta emoción podría ser una señal para protegerte.",
      "Eres lo suficientemente fuerte para superar esta emoción.",
      "Cuando el enfado disminuya, podrás ver la situación con más claridad.",
      "Encuentra una actividad que pueda calmar tu mente.",
      "Esta emoción no es permanente. Pasará pronto.",
      "Sigues siendo amado/a y un ser valioso.",
      "Por ahora, solo respira y concéntrate en calmar tu mente.",
      "No es tu culpa. Hiciste lo mejor que pudiste.",
      "Espera hasta que esta ola de emoción se calme.",
      "Cuando estés enfadado/a, piensa en las personas que te apoyan.",
      "Puedes crecer más fuerte a través de esta emoción.",
      "Está bien. Respeta todas las emociones que sientes ahora mismo.",
      "Esta emoción es solo una parte de ti, no todo tu ser.",
      "Puedes encontrar la paz. Lentamente, paso a paso.",
      "El enfado a veces puede ser un poderoso motivador para el cambio.",
      "Abraza tu corazón cálidamente. Porque eres precioso/a.",
      "Esta emoción te hará más fuerte.",
      "No fuerces nada ahora mismo. Deja que fluya naturalmente.",
      "Tienes la sabiduría y el coraje para superar esto.",
      "Lo que necesitas cuando estás enfadado/a no es culpa, sino comprensión y consuelo.",
      "Cuando esta emoción pase, serás aún más fuerte.",
      "De ninguna manera eres débil. La emoción que sientes es natural.",
      "Está bien, la calma te estará esperando al final de esta emoción.",
      "Mi corazón siempre estará contigo hasta que tu mente encuentre la paz de nuevo.",
      "Esta emoción no es tu culpa, así que no te culpes.",
    ],
    EmotionCategory.sad: [
      "Está bien estar triste ahora. Puedes llorar todo lo que quieras.",
      "No estás solo/a. Estoy, estamos aquí para ti.",
      "Esta tristeza también pasará. Solo aguanta un poco más.",
      "Si vienen las lágrimas, no las contengas. Déjalas fluir. Podría aligerar tu corazón.",
      "No puedo entender completamente tu dolor, pero te ofrezco mi más sincero pésame.",
      "Como dice el refrán 'el tiempo lo cura todo', esta tristeza se desvanecerá gradualmente.",
      "Eres una persona preciosa, digna de suficiente amor.",
      "Espero que no te quedes en la tristeza por mucho tiempo. Tienes derecho a ser feliz.",
      "Quiero envolver tu corazón como una manta cálida.",
      "Está bien si no todo mejora de una vez.",
      "Si no quieres hacer nada, está bien. Puedes descansar ahora.",
      "Después de que pase esta oscuridad, seguramente vendrá una mañana brillante.",
      "No es tu culpa. La tristeza le puede llegar a cualquiera.",
      "Que un pequeño consuelo sea una gran fuerza para tu corazón.",
      "Eres lo suficientemente fuerte para superar esta tristeza.",
      "La tristeza te convertirá en una persona más profunda.",
      "Por ahora, no pienses en nada y solo concéntrate en cuidar tu corazón.",
      "Quiero aligerar el peso de esta tristeza, aunque solo sea un poco.",
      "Estaré contigo hasta el día en que puedas sonreír de nuevo.",
      "Recuerda, sigues siendo hermoso/a y valioso/a.",
      "Cuando la tristeza te invada, piensa en las personas que te aman.",
      "Esta tristeza no es todo de ti. Tienes más partes brillantes dentro de ti.",
      "La cálida luz del sol también brillará eventualmente en tu corazón.",
      "Es duro ahora, pero definitivamente mejorará. Te lo prometo.",
      "No te juzgo por sentirte triste. Solo quiero abrazarte.",
      "Este tiempo doloroso eventualmente se convertirá en una base para tu crecimiento.",
      "No estás solo/a. En algún lugar de este mundo, hay un corazón que te entiende.",
      "La luz seguramente espera al final del túnel de la tristeza.",
      "Por ahora, solo acepta tu tristeza tal como es.",
      "Estaré en silencio a tu lado hasta que tus lágrimas se sequen.",
      "Espero que puedas encontrar pequeñas alegrías incluso en la tristeza.",
      "Eres precioso/a. Tu valor no cambia debido a esta tristeza.",
      "Cuando esta tristeza pase, serás más maduro/a.",
      "Rezo para que tu corazón encuentre la paz de nuevo.",
      "Por ahora, detente y siente plenamente tus emociones.",
      "Está bien. La tristeza puede ser parte del proceso de curación.",
      "Puedes levantarte de nuevo. Lentamente, a tu propio ritmo.",
      "Esta tristeza te hará más fuerte. Créelo.",
      "Encuentra algo que pueda consolar tu corazón. Música, películas o una charla con un amigo/a.",
      "La tristeza es una emoción natural. No te presiones demasiado.",
      "Tienes la fuerza para soportar esta tristeza. Cree en tu fuerza interior.",
      "Puede parecer oscuro ahora, pero el sol seguramente saldrá de nuevo.",
      "No tomo tu tristeza a la ligera. Respeto su profundidad.",
      "Que este tiempo de tristeza sea un tiempo de descanso y recuperación para ti.",
      "Está bien llorar lo suficiente. Las lágrimas no son una señal de debilidad.",
      "No dejes que la tristeza te consuma. Eres más fuerte que eso.",
      "Eres amado/a. Incluso en este momento.",
      "Cuando esta tristeza pase, se desplegará un nuevo capítulo en tu vida.",
      "Espera pacientemente hasta que tu corazón se recupere.",
      "Puedes superar esta tristeza y avanzar hacia un futuro más brillante.",
      "La tristeza no te define. Eres más que eso.",
      "Está bien, esta tristeza será una oportunidad para entenderte más profundamente.",
      "Así como tus lágrimas se convierten en estrellas que iluminan el cielo nocturno, la tristeza también tendrá significado.",
      "Por ahora, solo escucha a tu corazón. ¿Qué quiere?",
      "Esta tristeza te convertirá en una persona más cálida.",
      "No estás solo/a. Hay personas que compartirán esta tristeza contigo.",
      "El tiempo curará todas las heridas. Solo aguanta un poco más.",
      "Que la tristeza en tu corazón se derrita como la nieve.",
      "Aunque sea difícil ahora, seguramente llegará un día para sonreír de nuevo.",
      "Te volverás más fuerte a través de esta tristeza.",
      "La tristeza a veces nos enseña cosas preciosas.",
      "Tómate un tiempo tranquilo para que tu corazón descanse.",
      "Esta tristeza no es tu culpa. Le puede pasar a cualquiera.",
      "Eres digno/a de suficiente amor. Sin cambios incluso en la tristeza.",
      "Cuando pases por este túnel oscuro, encontrarás una luz más brillante.",
      "Intentaré entender tu tristeza. Dímelo en cualquier momento.",
      "Por ahora, solo siente tus emociones tal como son. Está bien.",
      "Esta tristeza puede detener temporalmente tu vida, pero no puede terminarla.",
      "Puedes ser feliz de nuevo. No pierdas esa creencia.",
      "La tristeza es como una nube pasajera. Pronto se verá un cielo despejado.",
      "Te envío un cálido consuelo para que tu corazón pueda sanar.",
      "Esta tristeza te hará crecer como una persona más profunda y amplia.",
      "No estás solo/a. Incluso en lugares invisibles, la gente te está animando.",
      "Es duro ahora, pero esto también pasará. Ánimo.",
      "Respeto tu tristeza. Y te animaré para que te levantes de nuevo.",
      "Esta tristeza puede ser una oportunidad para tu crecimiento.",
      "Eres lo suficientemente fuerte para manejar esta tristeza.",
      "Por ahora, solo acaricia tu corazón. Dile 'buen trabajo'.",
      "La tristeza no es eterna. No pierdas la esperanza.",
      "Sigues brillando. Incluso detrás de la sombra de la tristeza.",
      "Te volverás más maduro/a a través de esta tristeza.",
      "Espero sinceramente que tu corazón se llene de alegría de nuevo.",
      "La tristeza a veces nos lleva a lugares más profundos. Puedes descubrir un nuevo tú allí.",
      "Por ahora, solo descansa. Tu corazón necesita tiempo para recuperarse.",
      "Naciste para ser amado/a. Esta tristeza no puede cambiar ese hecho.",
      "Que una mayor felicidad florezca donde esta tristeza ha pasado.",
      "Eres un ser precioso. Ninguna tristeza puede disminuir tu valor.",
      "Está bien derramar lágrimas ahora. Esas lágrimas limpiarán tu corazón.",
      "Esta tristeza no te romperá. Te levantarás de nuevo.",
      "Siempre estaré a tu lado hasta que tu corazón encuentre la paz.",
      "La tristeza no es tu culpa. Es solo una prueba de que tienes un corazón tan puro y tierno.",
      "Esta experiencia de tristeza te convertirá en una persona más empática.",
      "No estás solo/a. Hay personas que entienden y apoyan tu tristeza.",
      "Es duro ahora, pero el crecimiento seguramente esperará al final de esta tristeza.",
      "Superarás esta tristeza y te convertirás en una persona aún más radiante.",
      "La tristeza a veces nos hace darnos cuenta del valor de la verdadera felicidad.",
      "Que tu corazón vuelva a ser brillante y soleado como un cálido día de primavera.",
      "Esta tristeza es solo una sombra fugaz en tu vida. Pronto se disipará.",
      "Sigues siendo fuerte y hermoso/a. Tu luz no se apaga ni siquiera en la tristeza.",
    ],
    EmotionCategory.afraid: [
      "El miedo que sientes ahora es natural. No es tu culpa.",
      "No estás solo/a. Permaneceré a tu lado.",
      "Este miedo también pasará. Estás a salvo.",
      "Intenta respirar profundamente. Exhalar lentamente ayudará a calmar tu mente.",
      "Eres mucho más fuerte y valiente de lo que piensas.",
      "En lugar de luchar contra el miedo, simplemente acompáñalo. Pronto disminuirá.",
      "En este momento, estás en un lugar seguro.",
      "Así como una pequeña luz puede iluminar una oscuridad profunda, un pequeño coraje puede vencer un gran miedo.",
      "Está bien. Es normal que todo se sienta incierto a veces.",
      "No dejes que esta ansiedad te domine por completo.",
      "Ya tienes la fuerza dentro de ti para superar este miedo.",
      "Un paso a la vez, incluso un paso muy pequeño está bien. Lo importante es que estás avanzando.",
      "El miedo puede ser una señal de que ha llegado una oportunidad para crecer.",
      "Ayudaré a tu corazón a encontrar la paz.",
      "No te preocupes. Todo saldrá bien al final.",
      "Estás protegido/a. Nada puede hacerte daño descuidadamente.",
      "No dejes que este miedo bloquee tu potencial.",
      "Intenta sostener algo cálido o escuchar música reconfortante.",
      "Está bien, el miedo es como una sombra sin sustancia.",
      "Eres precioso/a. Este miedo no disminuye tu valor.",
      "Intenta hablar honestamente sobre tus sentimientos con alguien.",
      "Esto también pasará. La ansiedad que sientes ahora no es para siempre.",
      "Has superado muchas dificultades antes. Puedes hacerlo esta vez también.",
      "El miedo es solo una reacción natural a lo desconocido.",
      "Piensa en las personas que te apoyan y te aman.",
      "Cuando este miedo disminuya, el mundo volverá a verse brillante.",
      "Está bien no decidir nada ahora mismo. Espera hasta que tu mente se calme.",
      "Estás a salvo, amado/a y apoyado/a.",
      "Este miedo podría no ser para detenerte, sino para hacerte mirar atrás por un momento.",
      "Eres valiente. Tú, que intentas avanzar incluso sintiendo miedo, eres verdaderamente valiente.",
      "Cree que todo estará bien. Esa creencia será tu fuerza.",
      "Tienes la capacidad de controlar esta situación.",
      "El miedo a menudo se siente exagerado, más grande de lo que realmente es.",
      "Encuentra un lugar pacífico en tu mente y quédate allí un rato.",
      "Este miedo te hará más fuerte y sabio/a.",
      "Está bien. Respeta todas las emociones que sientes ahora mismo.",
      "Recuerda que no estás solo/a. Siempre hay alguien de tu lado.",
      "Cuando esta ola de miedo pase, verás un mar en calma.",
      "Escucha tu voz interior. La respuesta podría estar allí.",
      "El miedo puede ser un trampolín para tu crecimiento.",
      "Por ahora, solo concéntrate en sentirte seguro/a.",
      "Tienes suficiente potencial para superar este miedo.",
      "El mundo puede sentirse aterrador a veces, pero siempre hay esperanza a tu lado.",
      "El miedo a veces puede ser una señal que anuncia el comienzo del cambio.",
      "Mereces plenamente el amor. El miedo no puede ocultar ese hecho.",
      "Cuando este momento pase, serás aún más valiente.",
      "De ninguna manera eres débil. Sentir miedo es humano.",
      "Está bien. Un nuevo comienzo podría estar esperando al final de este miedo.",
      "Este espacio te protegerá para que tu corazón pueda encontrar la paz de nuevo.",
      "El miedo no es tu culpa. A veces el mundo cambia demasiado rápido.",
      "Este miedo no es un muro para detenerte, sino un obstáculo para saltar.",
      "Estás a salvo. Por este momento, está bien dejar ir todas las preocupaciones.",
      "El miedo es solo tu sombra, no tú mismo/a.",
      "Está bien, esta ansiedad pronto pasará. Puedes encontrar la paz de nuevo.",
      "Hay una semilla de coraje dentro de ti. Riégala y dale sol.",
      "No dejes que este miedo oculte tu luz. Todavía puedes brillar intensamente.",
      "Un paso a la vez, ve despacio. No hay necesidad de apresurarse.",
      "Tienes tanto la sabiduría como la fuerza para manejar este miedo.",
      "El miedo a menudo parece poner a prueba cuán valientes podemos ser.",
      "Por ahora, solo recupera el aliento y siente el suelo firme bajo tus pies.",
      "No estás solo/a. Hay alguien con quien puedes compartir este miedo.",
      "Recuerda que este miedo no es tu culpa. Esto no es por ti.",
      "Cierra los ojos por un momento y recuerda el momento más cómodo que hayas tenido.",
      "El miedo es una emoción natural. Sentirlo no significa que seas débil.",
      "Este miedo podría ser una señal para protegerte. Observa lo que necesitas.",
      "Eres lo suficientemente fuerte para superar este miedo. Cree en ti mismo/a.",
      "Cuando el miedo disminuya, podrás ver la situación con más claridad.",
      "Encuentra una actividad segura que pueda calmar tu mente.",
      "Este miedo no es permanente. Desaparecerá algún día.",
      "Sigues siendo amado/a y un ser valioso, incluso con miedo.",
      "Por ahora, solo reconoce tu emoción y obsérvala pasar.",
      "No es tu culpa. Ya estás haciendo lo mejor que puedes.",
      "Está bien quedarte aquí hasta que esta ola de miedo se calme.",
      "Cuando tengas miedo, piensa en los rostros de quienes te apoyan y te aman.",
      "Puedes crecer y volverte más fuerte a través de este miedo.",
      "Está bien. Cada emoción que sientes ahora es parte de ti. Trátala con aprecio.",
      "Este miedo no te define. Eres mucho más grande que eso.",
      "Puedes encontrar la paz. Muy lentamente, a tu propio ritmo.",
      "El miedo a veces nos indica que exploremos nuevos caminos.",
      "Abraza tu corazón cálidamente. Te lo mereces.",
      "Este miedo te hará más resistente. Puedes superarlo.",
      "No fuerces nada ahora mismo. Deja que tu mente fluya naturalmente.",
      "Ya tienes todo lo que necesitas para superar esto. Dentro de ti.",
      "Lo que necesitas cuando tienes miedo no es culpa, sino ánimo cálido y apoyo.",
      "Cuando este miedo pase, habrás crecido un poco más.",
      "De ninguna manera eres débil. El miedo es solo el preludio del coraje.",
      "Está bien, la paz y la estabilidad seguramente te estarán esperando al final de este miedo.",
      "Este espacio siempre estará contigo para que tu corazón pueda sentirse seguro/a de nuevo.",
      "Este miedo no es tu culpa, así que por favor no te culpes. Eres precioso/a.",
    ],
  };

  @override
  List<String> getPhrasesForCategory(EmotionCategory category) {
    return _phrases[category] ??
        _phrases[EmotionCategory.general] ??
        ["No te preocupes, todo saldrá bien."];
  }

  @override
  String getRandomPhraseForCategory(EmotionCategory category) {
    final List<String> categoryPhrases = getPhrasesForCategory(category);
    if (categoryPhrases.isEmpty) {
      // 만약 특정 카테고리 문구가 비었으면, general에서 가져오거나 기본값 반환
      final List<String> generalPhrases = getPhrasesForCategory(
        EmotionCategory.general,
      );
      if (generalPhrases.isEmpty) {
        return "No te preocupes, todo saldrá bien."; // 최후의 기본값
      }
      return generalPhrases[_random.nextInt(generalPhrases.length)];
    }
    return categoryPhrases[_random.nextInt(categoryPhrases.length)];
  }
}
